name: "CONFIG COLLECTOR"
on:
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Execute PHP script
        run: |
          php bot.php
          git config credential.helper store
      - name: Configure Git
        run: |
          git config --global user.email "vip.mahditaheri@gmail.com"
          git config --global user.name "MhdiTaheri"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/CattMurr/FREE-PROXY.git
      - name: Push changes with rebase
        run: |
          git add -A
          git commit -m "V0.2 🚀 - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git pull --rebase origin main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
